# Site settings
title: Rorys Jekyll Bootstrap
email: your-email@domain.com
description: "This is Rorys Jekyll Site"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
#markdown: kramdown
permalink: pretty

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
#baseurl: 
